DROP TABLE BOOKING;



CREATE TABLE BOOKING(
  BOOKING_ID int NOT NULL PRIMARY KEY, 
  START_DATETIME VARCHAR(20) NOT NULL,
  END_DATETIME VARCHAR(20) NOT NULL,
  CAPACITY VARCHAR(20) NOT NULL,
  FIRST_NAME VARCHAR(20) NOT NULL,
  LAST_NAME VARCHAR(20) NOT NULL
);

INSERT INTO BOOKING ( BOOKING_ID, START_DATETIME, END_DATETIME, CAPACITY, FIRST_NAME, LAST_NAME  ) VALUES (1, '30/03/2017', '31/03/2017','30','Sam', 'Horn');
INSERT INTO BOOKING ( BOOKING_ID, START_DATETIME, END_DATETIME, CAPACITY, FIRST_NAME, LAST_NAME  ) VALUES (2, '1/04/2017', '2/04/2017','20','Amir', 'Khan');
INSERT INTO BOOKING ( BOOKING_ID, START_DATETIME, END_DATETIME, CAPACITY, FIRST_NAME, LAST_NAME  ) VALUES (3, '3/04/2017', '4/04/2017','45','Blow', 'Jobi');
INSERT INTO BOOKING ( BOOKING_ID, START_DATETIME, END_DATETIME, CAPACITY, FIRST_NAME, LAST_NAME  ) VALUES (4, '05/04/2017', '06/04/2017','50','Givitumy','Neil');
